# AI agents: MLX model picker, agent packages, agent config files.
# All content moved verbatim from home.nix.
{ config, pkgs, ... }:

let
  dotfiles = "${config.home.homeDirectory}/dotfiles";
in
{
  # ============================================================
  # MLX CLAUDE MODEL PICKER
  #
  # Generated by Home Manager at:
  # ~/.local/bin/cc-mlx-picker
  #
  # It queries MLX Serve at every launch and lets you choose a
  # currently available model. It does not modify Claude settings.
  # ============================================================

  home.file.".local/bin/cc-mlx-picker" = {
    executable = true;

    text = ''
      #!/usr/bin/env bash
      set -euo pipefail

      endpoint="''${MLX_ENDPOINT:-http://macpro:11234}"

      if ! command -v jq >/dev/null 2>&1; then
        printf 'Error: jq is required but was not found in PATH.\n' >&2
        exit 1
      fi

      models_json="$(
        curl --fail --silent --show-error \
          "''${endpoint}/v1/models"
      )" || {
        printf 'Error: unable to reach MLX Serve at %s/v1/models\n' "$endpoint" >&2
        exit 1
      }

      mapfile -t models < <(
        printf '%s\n' "$models_json" |
          jq -r '
            .data[]
            | select((.state // "unknown") != "error")
            | .id
          ' |
          sort -f
      )

      if ((''${#models[@]} == 0)); then
        printf 'No usable models were returned by %s/v1/models\n' "$endpoint" >&2
        exit 1
      fi

      printf '\nMLX Serve: %s\n\n' "$endpoint"

      for i in "''${!models[@]}"; do
        printf '  %d) %s\n' "$((i + 1))" "''${models[$i]}"
      done

      printf '\nChoose a model [1-%d] (q to quit): ' "''${#models[@]}"
      read -r choice

      case "$choice" in
        q | Q | "")
          exit 0
          ;;
      esac

      if ! [[ "$choice" =~ ^[0-9]+$ ]] || \
        ((choice < 1 || choice > ''${#models[@]})); then
        printf 'Invalid selection.\n' >&2
        exit 1
      fi

      model="''${models[$((choice - 1))]}"

      printf '\nStarting Claude Code with: %s\n\n' "$model"

      exec env \
        ANTHROPIC_AUTH_TOKEN="ollama" \
        ANTHROPIC_API_KEY="" \
        ANTHROPIC_BASE_URL="$endpoint" \
        claude --model "$model"
    '';
  };

  # ============================================================
  # AGENT PACKAGES
  #
  # Declared in home.nix's "AI agents" package group; other
  # packages stay in modules/packages.nix.
  # ============================================================

  home.packages = with pkgs; [
    # AI agents
    pi-coding-agent
    opencode
  ];

  # ============================================================
  # PI CODING AGENT
  # ============================================================

  home.file.".pi/agent/settings.json" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/.pi/agent/settings.json";
    force = true;
  };

  home.file.".pi/agent/models.json" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/.pi/agent/models.json";
    force = true;
  };

  # ============================================================
  # SHARED AGENTS
  # ============================================================

  home.file.".claude/CLAUDE.md" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/AGENTS.md";
    force = true;
  };

  home.file.".codex/AGENTS.md" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/AGENTS.md";
    force = true;
  };

  home.file.".config/opencode/AGENTS.md" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/AGENTS.md";
    force = true;
  };

  home.file.".claude/settings.json" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/.claude/settings.json";
    force = true;
  };

  home.file.".config/opencode/opencode.json" = {
    source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/.config/opencode/opencode.json";
    force = true;
  };
}
