{ config, pkgs, user, ... }:

let
  system = pkgs.stdenv.hostPlatform.system;
  isDarwin = builtins.match ".+-darwin" system != null;
  isLinux = builtins.match ".+-linux" system != null;
  dotfiles = "${config.home.homeDirectory}/dotfiles";
in
{
  home.username = user;
  # /Users on macOS, /home on Linux.
  home.homeDirectory = if isLinux then "/home/${user}" else "/Users/${user}";
  home.stateVersion = "24.11";

  # ============================================================
  # DEVELOPMENT TOOLS
  # ============================================================

  home.packages = with pkgs; [
    # CLI
    ripgrep
    fd
    fzf
    jq
    yq
    tree
    bat
    eza
    btop
    htop
    wget
    curl
    unzip
    zip
    ollama
    tmux

    # Git
    git
    git-lfs
    gh
    lazygit

    # Editor
    neovim

    # Shell
    starship
    zoxide

    # Python
    python3
    uv
    ruff
    basedpyright

    # JavaScript / TypeScript
    nodejs
    prettier
    bun

    # Go
    go
    gopls

    # Rust
    rustc
    cargo
    rustfmt
    rust-analyzer

    # Lua
    lua-language-server
    stylua

    # Shell
    bash-language-server
    shfmt

    # C / C++
    gcc
    cmake
    gnumake
    pkg-config

    # Containers
    docker
    docker-compose

    # AI agents
    pi-coding-agent
    opencode

    # Fonts
    nerd-fonts.hack
  ]
  # Docker on macOS goes through colima; Linux uses its native runtime.
  ++ (if isDarwin then [ colima ] else [])
  # Claude Code CLI - the macOS host receives it via the claude-code cask.
  ++ (if isLinux then [ nodePackages."@anthropic-ai/claude-code" ] else []);

  # ============================================================
  # ENVIRONMENT
  # ============================================================

  fonts.fontconfig.enable = true;

  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
    PAGER = "less";

    # Default terminal Ollama server: Ollama natif on macpro.
    OLLAMA_HOST = "http://macpro:11434";
  };

  # ============================================================
  # MLX CLAUDE MODEL PICKER
  #
  # Generated by Home Manager at:
  # ~/.local/bin/cc-mlx-picker
  #
  # It queries MLX Serve at every launch and lets you choose a
  # currently available model. It does not modify Claude settings.
  # ============================================================

  home.file.".local/bin/cc-mlx-picker" = {
    executable = true;

    text = ''
      #!/usr/bin/env bash
      set -euo pipefail

      endpoint="''${MLX_ENDPOINT:-http://macpro:11234}"

      if ! command -v jq >/dev/null 2>&1; then
        printf 'Error: jq is required but was not found in PATH.\n' >&2
        exit 1
      fi

      models_json="$(
        curl --fail --silent --show-error \
          "''${endpoint}/v1/models"
      )" || {
        printf 'Error: unable to reach MLX Serve at %s/v1/models\n' "$endpoint" >&2
        exit 1
      }

      mapfile -t models < <(
        printf '%s\n' "$models_json" |
          jq -r '
            .data[]
            | select((.state // "unknown") != "error")
            | .id
          ' |
          sort -f
      )

      if ((''${#models[@]} == 0)); then
        printf 'No usable models were returned by %s/v1/models\n' "$endpoint" >&2
        exit 1
      fi

      printf '\nMLX Serve: %s\n\n' "$endpoint"

      for i in "''${!models[@]}"; do
        printf '  %d) %s\n' "$((i + 1))" "''${models[$i]}"
      done

      printf '\nChoose a model [1-%d] (q to quit): ' "''${#models[@]}"
      read -r choice

      case "$choice" in
        q | Q | "")
          exit 0
          ;;
      esac

      if ! [[ "$choice" =~ ^[0-9]+$ ]] || \
        ((choice < 1 || choice > ''${#models[@]})); then
        printf 'Invalid selection.\n' >&2
        exit 1
      fi

      model="''${models[$((choice - 1))]}"

      printf '\nStarting Claude Code with: %s\n\n' "$model"

      exec env \
        ANTHROPIC_AUTH_TOKEN="ollama" \
        ANTHROPIC_API_KEY="" \
        ANTHROPIC_BASE_URL="$endpoint" \
        claude --model "$model"
    '';
  };

  # ============================================================
  # ZSH
  # ============================================================

  programs.zsh = {
    enable = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    initContent = ''
      bindkey '^f' autosuggest-accept
      setopt interactivecomments

      # Default terminal Ollama server: Ollama natif on macpro.
      export OLLAMA_HOST="http://macpro:11434"

      # Never export ANTHROPIC_BASE_URL globally.
      # MLX-specific variables are isolated in cc-mlx-picker.

      # API keys are local, outside the Nix store and ignored by Git.
      # Expected file: ~/dotfiles/secrets/env
      if [ -f "$HOME/dotfiles/secrets/env" ]; then
        source "$HOME/dotfiles/secrets/env"
      fi
    '';

    shellAliases = {
      # ============================================================
      # NAVIGATION / GIT / EDITOR / FILES
      # ============================================================

      # Navigation
      ".." = "cd ..";

      # Git
      add = "git add .";
      push = "git push";
      pull = "git pull";
      gs = "git status";
      lg = "lazygit";
      m = "git switch main";

      # Neovim
      v = "nvim";
      vi = "nvim";

      # Files
      ll = "eza -la";
      cat = "bat";

      # Generic agents
      cc = "claude --dangerously-skip-permissions";
      oc = "opencode";

      # ============================================================
      # OLLAMA NATIF VIA TAILSCALE
      #
      # macpro:11434 -> Ollama natif sur macpro
      # taichi:11434 -> Ollama natif sur Taichi
      #
      # Aucun modèle n'est forcé.
      # ============================================================

      # Default server, inherited from OLLAMA_HOST.
      ol = "ollama";
      ol-list = "ollama list";

      # Mac Pro — native Ollama.
      ol-macpro =
        ''OLLAMA_HOST="http://macpro:11434" ollama'';

      # Taichi — native Ollama (Tailscale name; on taichi itself it
      # simply resolves to this box).
      ol-taichi =
        ''OLLAMA_HOST="http://taichi:11434" ollama'';

      # Local Ollama on this machine.
      ol-local =
        ''OLLAMA_HOST="http://127.0.0.1:11434" ollama'';

      # ============================================================
      # MLX SERVE SUR MACPRO VIA TAILSCALE
      #
      # macpro:11234    -> API Ollama-compatible
      # macpro:11234/v1 -> API OpenAI-compatible
      # macpro:11234    -> API Anthropic-compatible
      #
      # Aucun tunnel SSH requis.
      # ============================================================

      # CLI Ollama connected to MLX Serve.
      ol-mlx-macpro =
        ''OLLAMA_HOST="http://macpro:11234" ollama'';

      ol-mlx-list =
        ''OLLAMA_HOST="http://macpro:11234" ollama list'';

      ol-mlx-ps =
        ''OLLAMA_HOST="http://macpro:11234" ollama ps'';

      # Usage: ol-mlx-run <model-name>
      ol-mlx-run =
        ''OLLAMA_HOST="http://macpro:11234" ollama run'';

      # Diagnostics MLX Serve.
      mlx-status =
        ''curl -sS http://macpro:11234/api/tags'';

      mlx-models =
        ''curl -sS http://macpro:11234/v1/models'';

      # Claude Code + MLX Serve interactive picker.
      cc-mlx-macpro =
        ''$HOME/.local/bin/cc-mlx-picker'';

      # ============================================================
      # PI
      #
      # Providers and models are defined in:
      # ~/.pi/agent/models.json
      #
      # Every backend alias explicitly selects the intended provider.
      # Use /model or Ctrl+L inside Pi to choose its configured model.
      # ============================================================

      # Pi default: defaultProvider/defaultModel in settings.json.
      pi-local = "pi";

      # Pi + Mac Pro native Ollama.
      pi-macpro =
        ''pi --provider macpro-ollama'';

      # Pi + Taichi native Ollama.
      pi-taichi =
        ''pi --provider taichi-ollama'';

      # Pi + Mac Pro MLX Serve.
      pi-mlx-macpro =
        ''pi --provider macpro-mlx'';

      # Pi + NVIDIA cloud. The provider reads $NVIDIA_API_KEY from
      # models.json / the environment loaded by secrets/env.
      pi-nvidia =
        ''pi --provider nvidia'';

      # Pi + direct NVIDIA model shortcuts.
      pinvidia =
        ''pi --provider nvidia --model nvidia/nemotron-3-super-120b-a12b'';

      pinvidia-ultra =
        ''pi --provider nvidia --model nvidia/nemotron-3-ultra-550b-a55b'';

      pideepseek =
        ''pi --provider nvidia --model deepseek-ai/deepseek-v4-pro-0813'';

      # ============================================================
      # TMUX — PERSISTENT AGENTS
      #
      # Ctrl+b then d: detach without stopping the agent.
      # `-A` creates the named session if absent, otherwise reconnects.
      # ============================================================

      # Claude Code + MLX Serve dynamic picker.
      cc-tmux-mlx-macpro =
        ''tmux new-session -A -s claude-mlx-macpro "$HOME/.local/bin/cc-mlx-picker"'';

      # Pi + Mac Pro native Ollama.
      pi-tmux-macpro =
        ''tmux new-session -A -s pi-macpro "pi --provider macpro-ollama"'';

      # Pi + Taichi native Ollama.
      pi-tmux-taichi =
        ''tmux new-session -A -s pi-taichi "pi --provider taichi-ollama"'';

      # Pi + Mac Pro MLX Serve.
      pi-tmux-mlx-macpro =
        ''tmux new-session -A -s pi-mlx-macpro "pi --provider macpro-mlx"'';

      # Pi + NVIDIA cloud.
      pi-tmux-nvidia =
        ''tmux new-session -A -s pi-nvidia "pi --provider nvidia"'';

      # tmux management.
      tnew = "tmux new-session -A -s";
      tmls = "tmux ls";
      tm = "tmux attach-session -d -t";
      tmwatch = "tmux attach-session -t";
      tkill = "tmux kill-session -t";
      tname = "tmux display-message -p '#S'";
      twindows = "tmux list-windows -a";
      tclients = "tmux list-clients";
      treload = "tmux source-file ~/.tmux.conf";
    }
    // pkgs.lib.optionalAttrs isDarwin {
      # ============================================================
      # MAC ONLY
      #
      # `ollama launch`, launchctl and `open -a` belong to Ollama
      # Desktop on macOS; taichi (Ubuntu) gets CLI equivalents in the
      # block below instead.
      # ============================================================

      # Claude Code + native Ollama macpro.
      cc-macpro =
        ''OLLAMA_HOST="http://macpro:11434" ollama launch claude'';

      # Claude Code + native Ollama taichi.
      cc-taichi =
        ''OLLAMA_HOST="http://taichi:11434" ollama launch claude'';

      # OpenCode + native Ollama macpro.
      oc-macpro =
        ''OLLAMA_HOST="http://macpro:11434" ollama launch opencode'';

      # OpenCode + native Ollama taichi.
      oc-taichi =
        ''OLLAMA_HOST="http://taichi:11434" ollama launch opencode'';

      # OpenCode + MLX Serve.
      oc-mlx-macpro =
        ''OLLAMA_HOST="http://macpro:11234" ollama launch opencode'';

      # ============================================================
      # OLLAMA APP + CLAUDE DESKTOP
      #
      # The aliases below open Ollama, never Claude directly.
      #
      # 127.0.0.1:11434 -> Ollama local
      # 127.0.0.1:12435 -> macpro:11434 via SSH
      # 127.0.0.1:11436 -> taichi:11434 via SSH
      # macpro:11234     -> MLX Serve via Tailscale
      # ============================================================

      # Start SSH tunnels for remote native Ollama servers.
      ol-tunnels = ''
        ssh -fN -L 127.0.0.1:12435:localhost:11434 maclino@macpro
        ssh -fN -L 127.0.0.1:11436:localhost:11434 delai@taichi
      '';

      # Stop only these exact two tunnels.
      ol-stop-tunnels = ''
        pkill -f "ssh -fN -L 127.0.0.1:12435:localhost:11434 maclino@macpro" || true
        pkill -f "ssh -fN -L 127.0.0.1:11436:localhost:11434 delai@taichi" || true
      '';

      # Test remote Ollama through local SSH tunnels.
      ol-tunnel-macpro =
        ''OLLAMA_HOST="http://127.0.0.1:12435" ollama'';

      ol-tunnel-taichi =
        ''OLLAMA_HOST="http://127.0.0.1:11436" ollama'';

      # Open Ollama Desktop using local Ollama.
      claude-local = ''
        launchctl setenv OLLAMA_HOST "http://127.0.0.1:11434"
        open -a Ollama
      '';

      # Open Ollama Desktop through Mac Pro SSH tunnel.
      claude-macpro = ''
        launchctl setenv OLLAMA_HOST "http://127.0.0.1:12435"
        open -a Ollama
      '';

      # Open Ollama Desktop through Taichi SSH tunnel.
      claude-taichi = ''
        launchctl setenv OLLAMA_HOST "http://127.0.0.1:11436"
        open -a Ollama
      '';

      # Open Ollama Desktop against MLX Serve.
      claude-mlx-macpro = ''
        launchctl setenv OLLAMA_HOST "http://macpro:11234"
        open -a Ollama
      '';

      # Pi + local MacBook Air oMLX.
      pi-omlx =
        ''pi --provider macbook-omlx'';

      # Pi + local oMLX, in tmux.
      pi-tmux-omlx =
        ''tmux new-session -A -s pi-omlx "pi --provider macbook-omlx"'';

      # ============================================================
      # TMUX AGENTS — OLLAMA DESKTOP (MAC)
      # ============================================================

      # Claude Code + native Ollama macpro.
      cc-tmux-macpro =
        ''tmux new-session -A -s claude-macpro "OLLAMA_HOST=http://macpro:11434 ollama launch claude"'';

      # Claude Code + native Ollama taichi.
      cc-tmux-taichi =
        ''tmux new-session -A -s claude-taichi "OLLAMA_HOST=http://taichi:11434 ollama launch claude"'';

      # OpenCode + native Ollama macpro.
      oc-tmux-macpro =
        ''tmux new-session -A -s opencode-macpro "OLLAMA_HOST=http://macpro:11434 ollama launch opencode"'';

      # OpenCode + native Ollama taichi.
      oc-tmux-taichi =
        ''tmux new-session -A -s opencode-taichi "OLLAMA_HOST=http://taichi:11434 ollama launch opencode"'';

      # OpenCode + MLX Serve.
      oc-tmux-mlx-macpro =
        ''tmux new-session -A -s opencode-mlx-macpro "OLLAMA_HOST=http://macpro:11234 ollama launch opencode"'';
    }
    // pkgs.lib.optionalAttrs isLinux {
      # ============================================================
      # TAICHI (UBUNTU) ONLY
      #
      # No Ollama Desktop on Linux: agents point straight at the
      # Anthropic-compatible endpoint of macpro via env.
      # - `cc*` runs the Claude Code CLI (Nix pkg, see home.packages)
      # - `oc*` runs opencode against the macpro providers declared
      #   in the shared opencode.json
      # ============================================================

      # Claude Code + Mac Pro native Ollama.
      cc-macpro =
        ''ANTHROPIC_API_KEY=ollama ANTHROPIC_BASE_URL=http://macpro:11434 claude'';

      # Claude Code + taichi's own Ollama.
      cc-taichi =
        ''ANTHROPIC_API_KEY=ollama ANTHROPIC_BASE_URL=http://127.0.0.1:11434 claude'';

      # OpenCode + Mac Pro Ollama: already the default model in
      # opencode.json.
      oc-macpro = "opencode";

      # OpenCode + Mac Pro MLX Serve (provider in opencode.json).
      oc-mlx-macpro =
        "opencode -m macpro-mlx/Qwen3.8-Flash-Next-oQ4e-MTP-128k";

      # ============================================================
      # SSH TUNNEL TO MACPRO (BACKUP IF TAILSCALE IS DOWN)
      #
      # 127.0.0.1:12435 -> macpro:11434 via SSH
      # ============================================================

      # Start the SSH tunnel to the Mac Pro Ollama server.
      ol-tunnels = ''
        ssh -fN -L 127.0.0.1:12435:localhost:11434 maclino@macpro
      '';

      # Stop only that exact tunnel.
      ol-stop-tunnels = ''
        pkill -f "ssh -fN -L 127.0.0.1:12435:localhost:11434 maclino@macpro" || true
      '';

      # Test Mac Pro Ollama through the local SSH tunnel.
      ol-tunnel-macpro =
        ''OLLAMA_HOST="http://127.0.0.1:12435" ollama'';

      # ============================================================
      # TMUX AGENTS — TAICHI
      # ============================================================

      # Claude Code + Mac Pro native Ollama.
      cc-tmux-macpro =
        ''tmux new-session -A -s claude-macpro "ANTHROPIC_API_KEY=ollama ANTHROPIC_BASE_URL=http://macpro:11434 claude"'';

      # Claude Code + taichi's own Ollama.
      cc-tmux-taichi =
        ''tmux new-session -A -s claude-taichi "ANTHROPIC_API_KEY=ollama ANTHROPIC_BASE_URL=http://127.0.0.1:11434 claude"'';

      # OpenCode + Mac Pro Ollama (default model in opencode.json).
      oc-tmux-macpro =
        ''tmux new-session -A -s opencode-macpro "opencode"'';

      # OpenCode + Mac Pro MLX Serve.
      oc-tmux-mlx-macpro =
        ''tmux new-session -A -s opencode-mlx-macpro "opencode -m macpro-mlx/Qwen3.8-Flash-Next-oQ4e-MTP-128k"'';
    };
  };

  # ============================================================
  # STARSHIP
  # ============================================================

  programs.starship = {
    enable = true;

    settings = {
      add_newline = false;

      format =
        "$directory$git_branch$git_status$cmd_duration$line_break$character";

      character = {
        success_symbol = "[❯](purple)";
        error_symbol = "[❯](red)";
      };

      cmd_duration.format = "[$duration]($style) ";
    };
  };

  # ============================================================
  # ZOXIDE
  # ============================================================

  programs.zoxide = {
    enable = true;
    enableZshIntegration = true;
  };

  # ============================================================
  # DOTFILES
  # ============================================================

  home.file.".config/wezterm" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.config/wezterm";
    force = true;
  };

  home.file.".config/nvim" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.config/nvim";
    force = true;
  };

  home.file.".config/herdr" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.config/herdr";
    force = true;
  };

  home.file.".claude/settings.json" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.claude/settings.json";
    force = true;
  };

  # ============================================================
  # PI CODING AGENT
  # ============================================================

  home.file.".pi/agent/settings.json" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.pi/agent/settings.json";
    force = true;
  };

  home.file.".pi/agent/models.json" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.pi/agent/models.json";
    force = true;
  };

  # ============================================================
  # SHARED AGENTS
  # ============================================================

  home.file.".claude/CLAUDE.md" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/AGENTS.md";
    force = true;
  };

  home.file.".codex/AGENTS.md" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/AGENTS.md";
    force = true;
  };

  home.file.".config/opencode/AGENTS.md" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/AGENTS.md";
    force = true;
  };

  home.file.".config/opencode/opencode.json" = {
    source =
      config.lib.file.mkOutOfStoreSymlink
        "${dotfiles}/home/.config/opencode/opencode.json";
    force = true;
  };
}